language: node_js
  node_js:
    - "node"
  cache: npm
  script: npm run build
  deploy:
    provider: pages
    skip_cleanup: true
    github_token: 'c20c71973b86'
    local_dir: dist
    on:
      branch: master
